runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: '1.0'
handlers:
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: .*\.jsp
  script: unused
  login: optional
  secure: optional
- url: /programs
  script: unused
  login: optional
  secure: optional
- url: /jobs
  script: unused
  login: optional
  secure: optional
- url: /create
  script: unused
  login: optional
  secure: optional
- url: /login
  script: unused
  login: optional
  secure: optional
- url: /sign_in
  script: unused
  login: optional
  secure: optional
- url: /post
  script: unused
  login: optional
  secure: optional
- url: /register
  script: unused
  login: optional
  secure: optional
